# Explore Montreal Exchange

Using python to inspect [Montréal Exchange](https://www.m-x.ca/en/trading/data/options-list) for option prices

## Imports

In [1]:
import sys
import requests
import bs4
import lxml
import pandas as pd
from datareader import get_list, get_price

In [2]:
versions = f"""
python vesion : {''.join((str(sys.version_info[0]),'.',str(sys.version_info[1]),'.',str(sys.version_info[2])))}
pandas version: {pd.__version__}
requests version: {requests.__version__}
bs4 version: {bs4.__version__}
lxml version: {lxml.__version__}
"""
print(versions)

python vesion : 3.11.5
pandas version: 2.1.0
requests version: 2.31.0
bs4 version: 4.12.2
lxml version: 5.3.0

## Get List of Options

In [47]:
# inspect list of index options
# can also choose from etf, equity, currency, weekly
df = get_list('index')
df

,Name of Underlying Instrument,Option Symbol,Underlying Symbol
0,S&P/TSX 60 Index Standard Options,SXO,TX60
1,S&P/TSX Capped Utilities Index Options,SXV,TTUT
2,S&P/TSX Composite Index Banks (Industry Group)...,SXJ,TXBA

## Get Option Prices for Symbol

In [6]:
current, df = get_price('AC')
# current data for symbol
current

,Last update,TICKER,Last price,Net change,Bid price,Ask price,30-day historical volatility
0,"February 19, 2025 at 9:52 p.m. (Real-time)",AC,0,0,0,0,29.92%

In [3]:
# option prices dataframe
df

                                    Calls                                  \
                    Expiry date Bid price Ask price Last price Net change
0    February 28, 2025 (Weekly)         0         0       2.05          0
1    February 28, 2025 (Weekly)         0         0       1.57          0
2    February 28, 2025 (Weekly)         0         0       1.11          0
3    February 28, 2025 (Weekly)         0         0       0.73          0
4    February 28, 2025 (Weekly)         0         0       0.43          0
..                          ...       ...       ...        ...        ...
307            January 15, 2027         0         0       2.27          0
308            January 15, 2027         0         0       1.81          0
309            January 15, 2027      0.90         0       1.56          0
310            January 15, 2027         0         0       0.96          0
311            January 15, 2027         0         0       0.43          0

                               Puts                                            \
    Open int. Vol. Strike Bid price Ask price Last price Net change Open int.
0           0    0   15.5         0         0       0.04          0         0
1           0    0   16.0         0         0       0.06          0         0
2           0    0   16.5         0         0       0.12          0        17
3          10    0   17.0         0         0       0.26          0        35
4          32    0   17.5         0         0       0.46          0        31
..        ...  ...    ...       ...       ...        ...        ...       ...
307        11    0   22.0         0         0       5.75          0         9
308        49    0   24.0         0         0       7.35          0         0
309        21    0   25.0         0         0       8.15          0        22
310       191    0   30.0         0         0      12.85          0         8
311        66    0   40.0         0         0      22.80          0         0


    Vol.
0      0
1      0
2      0
3      0
4      0
..   ...
307    0
308    0
309    0
310    0
311    0

[312 rows x 14 columns]

## Filter

In [5]:
df_calls = df['Calls'].copy()
df[(df_calls['Ask price'] != '0') | (df_calls['Bid price'] != '0')]

                                    Calls                                  \
                    Expiry date Bid price Ask price Last price Net change
11   February 28, 2025 (Weekly)         0      4.00       0.05          0
15   February 28, 2025 (Weekly)         0      0.23       0.04          0
23       March 7, 2025 (Weekly)         0      0.50       0.35          0
51      March 28, 2025 (Weekly)      0.25         0       0.63          0
64       April 4, 2025 (Weekly)      0.35         0       0.40          0
79            February 21, 2025         0      0.50       0.09          0
80            February 21, 2025         0      5.00       0.04          0
81            February 21, 2025         0      0.20       0.03          0
82            February 21, 2025         0      0.60       0.02          0
83            February 21, 2025         0      0.03       0.02          0
87            February 21, 2025         0      4.00       0.02          0
92            February 21, 2025         0      0.50       0.02          0
93            February 21, 2025         0      0.28       0.02          0
95            February 21, 2025         0      0.25       0.02          0
106              March 21, 2025         0      4.20       2.65          0
110              March 21, 2025         0      1.65       1.05          0
112              March 21, 2025      0.30         0       0.54          0
113              March 21, 2025         0      0.50       0.39          0
116              March 21, 2025         0      3.00       0.14          0
119              March 21, 2025      0.01         0       0.06          0
120              March 21, 2025         0      2.00       0.06          0
122              March 21, 2025         0      5.00       0.05          0
142              April 17, 2025         0      1.80       0.83          0
145              April 17, 2025         0      0.50       0.38          0
146              April 17, 2025         0      5.10       0.30          0
147              April 17, 2025         0      0.60       0.23          0
149              April 17, 2025         0      1.50       0.14          0
156              April 17, 2025         0      0.50       0.04          0
162              April 17, 2025         0      1.00       0.05          0
172                May 16, 2025         0      3.50       0.89          0
181                May 16, 2025         0      1.50       0.16          0
186                May 16, 2025         0      1.00       0.10          0
202               June 20, 2025         0      1.70       1.31          0
204               June 20, 2025         0      2.10       0.91          0
206               June 20, 2025      0.60      2.22       0.65          0
207               June 20, 2025         0      3.25       0.54          0
210               June 20, 2025         0      1.80       0.33          0
212               June 20, 2025      0.20         0       0.27          0
227               July 18, 2025         0      2.95       1.97          0
236               July 18, 2025         0      1.20       0.48          0
237               July 18, 2025         0      4.00       0.40          0
266          September 19, 2025         0      2.00       1.03          0
268          September 19, 2025         0      1.70       0.61          0
270          September 19, 2025         0      1.20       0.39          0
286           December 19, 2025         0      2.79       0.43          0
290            January 16, 2026      3.00      8.80       3.95          0
291            January 16, 2026         0      3.50       3.35          0
292            January 16, 2026         0      7.00       2.32          0
293            January 16, 2026         0      3.00       1.88          0
294            January 16, 2026      1.10      5.00       1.55          0
296            January 16, 2026         0      9.00       0.70          0
297            January 16, 2026      0.45         0       0.58          0
298            January 16, 2026         0      0.50       0.29          0
299            January 16, 2026      0.01         0       0.13          0
303            January 15, 2027      4.50         0       5.30          0
304            January 15, 2027      2.80      6.00       4.75          0
306            January 15, 2027      1.75         0       2.75          0
309            January 15, 2027      0.90         0       1.56          0

                               Puts                                            \
    Open int. Vol. Strike Bid price Ask price Last price Net change Open int.
11       2467    0   21.0         0         0       3.65          0        20
15       2364    0   23.0         0         0       5.65          0         0
23         15    0   18.0         0         0       0.88          0         0
51          0    0   18.0         0         0       1.11          0         0
64          0    0   19.0         0         0       1.88          0         0
79        696    0   18.0         0         0       0.64          0       183
80        883    0   18.5         0         0       1.12          0       111
81        754    0   19.0         0         0       1.60          0       646
82         44    0   19.5         0         0       2.10          0        95
83       1458    0   20.0         0      5.95       2.61          0        36
87      10690    0   22.0         0         0       4.60          0        13
92         49    0   24.5         0         0       7.10          0        30
93       2002    0   25.0         0         0       7.60          0        50
95        114    0   27.0         0         0       9.60          0         0
106        55    0   15.0         0         0       0.09          0       101
110       173    0   17.0         0      0.88       0.53          0      1269
112       679    0   18.0         0         0       1.04          0       191
113       407    0   18.5         0         0       1.39          0        67
116       307    0   20.0         0         0       2.68          0       105
119       535    0   21.5         0         0       4.15          0       260
120       601    0   22.0         0         0       4.65          0       220
122       476    0   23.0         0         0       5.60          0         0
142       348    0   18.0         0         0       1.27          0        76
145        40    0   19.5         0         0       2.34          0        58
146       120    0   20.0         0         0       2.76          0        40
147        25    0   20.5         0         0       3.20          0        25
149        61    0   21.5         0         0       4.20          0        22
156       179    0   25.0         0         0       7.60          0        35
162         0    0   31.0         0         0      13.60          0         0
172       124    0   18.5         0         0       1.78          0         7
181        27    0   23.0         0         0       5.70          0        11
186         8    0   26.0         0         0       8.65          0         0
202       369    0   18.0         0         0       1.65          0        99
204       190    0   19.0         0         0       2.27          0         0
206       220    0   20.0         0         0       3.00          0        89
207        10    0   20.5         0         0       3.40          0         0
210        65    0   22.0         0         0       4.75          0      1050
212        80    0   23.0         0         0       5.70          0        50
227         6    0   17.0         0         0       1.25          0        10
236         0    0   21.5         0         0       4.35          0         0
237        12    0   22.0         0         0       4.80          0         0
266       191    0   20.0         0         0       3.25          0        18
268        63    0   22.0         0         0       4.90          0         0
270        87    0   24.0         0         0       6.75          0        45
286       217    0   26.0         0         0       8.80          0         1
290       916    0   15.0         0      1.20       1.03          0       124
291       365    0   16.0         0      2.28       1.32          0       293
292       605    0   18.0         0         0       2.32          0        98
293        97    0   19.0         0         0       2.90          0        53
294       942    0   20.0         0         0       3.60          0       169
296       210    0   24.0         0         0       6.85          0        15
297      1707    0   25.0         0         0       7.85          0        50
298       928    0   30.0         0         0      12.70          0         0
299       304    0   40.0         0         0      22.70          0         0
303        78    0   15.0         0         0       1.78          0        53
304      5146    0   16.0         0         0       2.18          0      5070
306       262    0   20.0         0         0       4.35          0        39
309        21    0   25.0         0         0       8.15          0        22


    Vol.
11     0
15     0
23     0
51     0
64     0
79     0
80     0
81     0
82     0
83     0
87     0
92     0
93     0
95     0
106    0
110    0
112    0
113    0
116    0
119    0
120    0
122    0
142    0
145    0
146    0
147    0
149    0
156    0
162    0
172    0
181    0
186    0
202    0
204    0
206    0
207    0
210    0
212    0
227    0
236    0
237    0
266    0
268    0
270    0
286    0
290    0
291    0
292    0
293    0
294    0
296    0
297    0
298    0
299    0
303    0
304    0
306    0
309    0